# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path=r'C:\\Users\\intel\\Desktop\\python_proj\\chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://59a52cbf.ngrok.io/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(3)").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Abithaa")
    self.driver.find_element(By.NAME, "password").send_keys("sahithya")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Click Here to go to Your Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myDropdown > a:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myDropdown > a:nth-child(1)").click()
    self.driver.find_element(By.ID, "home").click()
  
obj=TestTest1()
obj.setup_method(method='POST')

obj.test_test1()
obj.teardown_method(method='POST')
